name: 'Semantic version release'
description: 'Evaluate version by semantic commit messages and create release'
author: 'Grumpy Programmer'
inputs:
  init-version:
    description: 'The init version of project default: 0.0.0'
    required: false
    default: '0.0.0'
  tag-prefix:
    description: 'The prefix of version tag, default: v'
    required: false
    default: 'v'
  assets:
    description: 'Assets files added to release, accept multiple paths, example: path/to/file.txt path/to/*.txt path/**/*.txt'
    required: false
    default: ''
outputs:
  tag:
    description: 'New tag'
  version:
    description: 'New version'
  released:
    description: 'If new version was released'
runs:
  using: 'node12'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
  post-if: 'success()'
