name: 'Semantic version release'
description: 'Evaluate version by semantic commit messages and create release'
author: 'Grumpy Programmer'
inputs:
  init-version:
    description: 'The init version of project default 0.0.0'
    default: '0.0.0'
  tag-prefix:
    description: 'The prefix of version tag, default v'
    default: 'v'
outputs:
  old-version:
    description: 'Old version'
  new-version:
    description: 'New version'
runs:
  using: 'node12'
  main: 'dist/main.js'
